name: Make/Zip CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: "KDE Comic plugin"
        path: build/*.comic
